import "~/styles/globals.css";

import { Sometype_Mono } from "next/font/google";
import Navbar from "~/components/Navbar";
import CursorHighlight from "~/components/CursorHighlight";
import Providers from "~/components/Providers";

const sometype = Sometype_Mono({
    subsets: ["latin"],
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${sometype.className}`}>
                <Providers>
                    {children}
                    <CursorHighlight />
                    <Navbar />
                </Providers>
            </body>
        </html>
    );
}
